name: build-java
on:
  push: { paths: ['services/**', 'proto/**'] }
  pull_request: { paths: ['services/**', 'proto/**'] }

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: aqua
          POSTGRES_USER: aqua
          POSTGRES_DB: aqua
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd "pg_isready -U aqua"
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Configure Testcontainers reuse (cache-friendly)
        run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      - name: Build & test
        working-directory: services/controlplane-java
        run: ./gradlew --no-daemon clean build