name: security-scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'  # weekly

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '0'