name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap
        run: make bootstrap

      - name: Lint canonical extensions
        run: make lint

      - name: Tests
        run: make test

      - name: Plan canonical migration (dry-run)
        run: python tools/migrate_extensions.py || true

      - name: Verify no pending renames on protected branches
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make canonical-verify
